def load_fixtures():
    return [
        # Matchweek 25
        ("Leeds United", "Nottm Forest"),
        ("Man United", "Tottenham"),
        ("Fulham", "Everton"),
        ("Burnley", "West Ham"),
        ("Arsenal", "Sunderland"),
        ("Wolves", "Chelsea"),
        ("Bournemouth", "Aston Villa"),
        ("Newcastle", "Brentford"),
        ("Brighton", "Crystal Palace"),
        ("Liverpool", "Man City"),

        # Matchweek 26
        ("Tottenham", "Newcastle"),
        ("Chelsea", "Leeds United"),
        ("Everton", "Bournemouth"),
        ("West Ham", "Man United"),
        ("Nottm Forest", "Wolves"),
        ("Aston Villa", "Brighton"),
        ("Crystal Palace", "Burnley"),
        ("Man City", "Fulham"),
        ("Sunderland", "Liverpool"),
        ("Brentford", "Arsenal"),

        # Matchweek 27
        ("Man City", "Newcastle"),
        ("Aston Villa", "Leeds United"),
        ("Nottm Forest", "Liverpool"),
        ("Brentford", "Brighton"),
        ("Chelsea", "Burnley"),
        ("West Ham", "Bournemouth"),
        ("Crystal Palace", "Wolves"),
        ("Sunderland", "Fulham"),
        ("Tottenham", "Arsenal"),
        ("Everton", "Man United"),

        # Matchweek 28
        ("Wolves", "Aston Villa"),
        ("Bournemouth", "Sunderland"),
        ("Brighton", "Nottm Forest"),
        ("Liverpool", "West Ham"),
        ("Newcastle", "Everton"),
        ("Burnley", "Brentford"),
        ("Leeds United", "Man City"),
        ("Fulham", "Tottenham"),
        ("Man United", "Crystal Palace"),
        ("Arsenal", "Chelsea"),

        # Matchweek 29
        ("Everton", "Burnley"),
        ("Bournemouth", "Brentford"),
        ("Leeds United", "Sunderland"),
        ("Wolves", "Liverpool"),
        ("Brighton", "Arsenal"),
        ("Man City", "Nottm Forest"),
        ("Fulham", "West Ham"),
        ("Aston Villa", "Chelsea"),
        ("Newcastle", "Man United"),
        ("Tottenham", "Crystal Palace"),

        # Matchweek 30
        ("West Ham", "Man City"),
        ("Crystal Palace", "Leeds United"),
        ("Burnley", "Bournemouth"),
        ("Man United", "Aston Villa"),
        ("Sunderland", "Brighton"),
        ("Nottm Forest", "Fulham"),
        ("Chelsea", "Newcastle"),
        ("Arsenal", "Everton"),
        ("Liverpool", "Tottenham"),
        ("Brentford", "Wolves"),

        # Matchweek 31
        ("Bournemouth", "Man United"),
        ("Brighton", "Liverpool"),
        ("Fulham", "Burnley"),
        ("Aston Villa", "West Ham"),
        ("Wolves", "Arsenal"),
        ("Man City", "Crystal Palace"),
        ("Everton", "Chelsea"),
        ("Leeds United", "Brentford"),
        ("Newcastle", "Sunderland"),
        ("Tottenham", "Nottm Forest"),

        # Matchweek 32
        ("Brentford", "Everton"),
        ("Man United", "Leeds United"),
        ("West Ham", "Wolves"),
        ("Chelsea", "Man City"),
        ("Crystal Palace", "Newcastle"),
        ("Sunderland", "Tottenham"),
        ("Arsenal", "Bournemouth"),
        ("Burnley", "Brighton"),
        ("Liverpool", "Fulham"),
        ("Nottm Forest", "Aston Villa"),

        # Matchweek 33
        ("Man City", "Arsenal"),
        ("Tottenham", "Brighton"),
        ("Crystal Palace", "West Ham"),
        ("Nottm Forest", "Burnley"),
        ("Brentford", "Fulham"),
        ("Aston Villa", "Sunderland"),
        ("Chelsea", "Man United"),
        ("Everton", "Liverpool"),
        ("Leeds United", "Wolves"),
        ("Newcastle", "Bournemouth"),

        # Matchweek 34
        ("Arsenal", "Newcastle"),
        ("West Ham", "Everton"),
        ("Man United", "Brentford"),
        ("Burnley", "Man City"),
        ("Fulham", "Aston Villa"),
        ("Brighton", "Chelsea"),
        ("Bournemouth", "Leeds United"),
        ("Sunderland", "Nottm Forest"),
        ("Wolves", "Tottenham"),
        ("Liverpool", "Crystal Palace"),

        # Matchweek 35
        ("Aston Villa", "Tottenham"),
        ("Chelsea", "Nottm Forest"),
        ("Everton", "Man City"),
        ("Man United", "Liverpool"),
        ("Brentford", "West Ham"),
        ("Leeds United", "Burnley"),
        ("Arsenal", "Fulham"),
        ("Wolves", "Sunderland"),
        ("Newcastle", "Brighton"),
        ("Bournemouth", "Crystal Palace"),

        # Matchweek 36
        ("Nottm Forest", "Newcastle"),
        ("Tottenham", "Leeds United"),
        ("Liverpool", "Chelsea"),
        ("Man City", "Brentford"),
        ("Fulham", "Bournemouth"),
        ("Sunderland", "Man United"),
        ("West Ham", "Arsenal"),
        ("Brighton", "Wolves"),
        ("Crystal Palace", "Everton"),
        ("Burnley", "Aston Villa"),

        # Matchweek 37
        ("Brentford", "Crystal Palace"),
        ("Bournemouth", "Man City"),
        ("Chelsea", "Tottenham"),
        ("Leeds United", "Brighton"),
        ("Newcastle", "West Ham"),
        ("Aston Villa", "Liverpool"),
        ("Arsenal", "Burnley"),
        ("Wolves", "Fulham"),
        ("Everton", "Sunderland"),
        ("Man United", "Nottm Forest"),

        # Matchweek 38
        ("Man City", "Aston Villa"),
        ("Brighton", "Man United"),
        ("Fulham", "Newcastle"),
        ("Tottenham", "Everton"),
        ("Liverpool", "Brentford"),
        ("Burnley", "Wolves"),
        ("Nottm Forest", "Bournemouth"),
        ("West Ham", "Leeds United"),
        ("Sunderland", "Chelsea"),
        ("Crystal Palace", "Arsenal"),
    ]
